import { PROVIDER_RULE_ADAPTERS } from "./provider-rule-renderer";
import {
  COMMAND_NAMESPACE,
  CACHE_DIR,
  RUNTIME_COMMANDS_DIR,
  PROMPT_TEMPLATES_DIR,
  PACK_PLUGIN_PATHS,
  PROVIDER_COMMAND_SUPPORT,
  WORKFLOW_COMMANDS,
  CLI_DIAGNOSTIC_COMMANDS,
  CANONICAL_COMMANDS,
  SLASH_COMMANDS,
  providerCommandSupport,
  providerInvocationFor,
  formatProviderUseLine,
  providerCommandPathsForRuntime,
  runtimeCommandCatalogPathsForPlan,
  type ProviderCommandStatus,
  type ProviderId,
  type ProviderCommandSupportEntry,
  type WorkflowCommandSpec,
} from "./catalog/provider-command-metadata";
import {
  buildCommandSurface,
  readInstalledCommandSurface,
  formatCommandSupportForPlan,
  activationMarkdown,
  renderRuntimeCommandFile,
  renderClaudeCommandFileFromSpec,
  renderAgentsCommandAliasesSection,
  buildManifest,
  type InstalledProviderSurface,
  type CommandSurfaceProvider,
  type CommandSurface,
  type InstalledCommandSurface,
  type Manifest,
} from "./catalog/command-rendering";
import {
  installPromptTemplates,
  installRuntimeCommandCatalog,
  installProviderCommandSurface,
  installClaudeNativeCommands,
  appendAgentsCommandAliases,
  installProviderNativeCommands,
  installProviderFallbackCommands,
  installCursorHarnessFallback,
  installGeminiHarnessFallback,
  mergeManifestProviders,
  fileReferencesActivation,
  writeFile,
  type InstallOptions,
  type WriteResult,
} from "./catalog/command-installation";

export {
  PROVIDER_RULE_ADAPTERS,
  COMMAND_NAMESPACE,
  CACHE_DIR,
  RUNTIME_COMMANDS_DIR,
  PROMPT_TEMPLATES_DIR,
  PACK_PLUGIN_PATHS,
  PROVIDER_COMMAND_SUPPORT,
  WORKFLOW_COMMANDS,
  CLI_DIAGNOSTIC_COMMANDS,
  CANONICAL_COMMANDS,
  SLASH_COMMANDS,
  providerCommandSupport,
  providerInvocationFor,
  formatProviderUseLine,
  providerCommandPathsForRuntime,
  runtimeCommandCatalogPathsForPlan,
  buildCommandSurface,
  readInstalledCommandSurface,
  formatCommandSupportForPlan,
  activationMarkdown,
  renderRuntimeCommandFile,
  renderClaudeCommandFileFromSpec,
  renderAgentsCommandAliasesSection,
  buildManifest,
  installPromptTemplates,
  installRuntimeCommandCatalog,
  installProviderCommandSurface,
  installClaudeNativeCommands,
  appendAgentsCommandAliases,
  installProviderNativeCommands,
  installProviderFallbackCommands,
  installCursorHarnessFallback,
  installGeminiHarnessFallback,
  mergeManifestProviders,
  fileReferencesActivation,
  writeFile,
};
export type {
  ProviderCommandStatus,
  ProviderId,
  ProviderCommandSupportEntry,
  WorkflowCommandSpec,
  InstalledProviderSurface,
  CommandSurfaceProvider,
  CommandSurface,
  InstalledCommandSurface,
  Manifest,
  InstallOptions,
  WriteResult,
};
