import type { EngineState } from '../state.js';

export async function coderNode(state: EngineState): Promise<EngineState> {
  if (!state.current) return state;

  const output = `// Generated by aix engine\n// Task: ${state.current.description}\n\nfunction solution() {\n  // TODO: implement ${state.current.description}\n}`;

  const tasks = state.tasks.map(t =>
    t.id === state.current!.id
      ? { ...t, status: 'done' as const, output, assignedRole: 'coder' as const }
      : t
  );

  return {
    ...state,
    tasks,
    current: { ...state.current, status: 'done' as const, output, assignedRole: 'coder' as const },
  };
}
