"""CLI entry point — Typer app with subcommands."""

import contextlib
import os
import uuid
from pathlib import Path
from typing import Any

import typer
from rich import print as rprint
from rich.panel import Panel
from rich.prompt import Prompt

from agentic_goal.config import PROJECT_CONFIG_PATH, load_config, validate_config
from agentic_goal.events import EventBus, JsonlSink, MarkdownSink, TerminalSink, set_event_bus
from agentic_goal.graph_builder import build_graph, get_checkpointer


def _friendly_error(exc: Exception) -> None:
    """Print a concise, human-readable error panel for common API failures."""
    msg = str(exc)
    if "credit balance is too low" in msg or "insufficient_quota" in msg:
        rprint(
            Panel(
                "[bold red]Insufficient credits[/bold red]\n\n"
                "Your API account has run out of credits.\n"
                "→ Anthropic: https://console.anthropic.com/settings/billing\n"
                "→ OpenAI:    https://platform.openai.com/settings/organization/billing",
                title="💳 Payment Required",
                border_style="red",
            )
        )
    elif "invalid x-api-key" in msg or "invalid_api_key" in msg or "authentication" in msg.lower():
        rprint(
            Panel(
                "[bold red]Invalid API key[/bold red]\n\n"
                "Check that your API key is correct and exported:\n"
                "  export ANTHROPIC_API_KEY=sk-ant-...\n"
                "  export OPENAI_API_KEY=sk-...",
                title="🔑 Authentication Error",
                border_style="red",
            )
        )
    elif "not_found_error" in msg or "model:" in msg:
        rprint(
            Panel(
                f"[bold red]Model not found[/bold red]\n\n{msg}\n\n"
                "Check your model name in ~/.config/agentic-goal/config.yaml",
                title="🤖 Unknown Model",
                border_style="red",
            )
        )
    elif "rate_limit" in msg or "rate limit" in msg.lower() or "429" in msg:
        rprint(
            Panel(
                "[bold yellow]Rate limit hit[/bold yellow]\n\n"
                "Too many requests. Wait a moment then try again.",
                title="⏳ Rate Limit",
                border_style="yellow",
            )
        )
    elif "Connection" in msg or "connect" in msg.lower() or "timeout" in msg.lower():
        rprint(
            Panel(
                "[bold red]Connection error[/bold red]\n\n"
                f"{msg}\n\nCheck your internet connection and try again.",
                title="🌐 Network Error",
                border_style="red",
            )
        )
    else:
        rprint(
            Panel(
                f"[bold red]{type(exc).__name__}[/bold red]\n\n{msg}",
                title="❌ Error",
                border_style="red",
            )
        )

app = typer.Typer(help="Agentic SDLC CLI: /goal -> plan -> rules -> tasks -> execute")

_CONFIG_TEMPLATE = """\
# agentic-goal project config
# Generated by: goal init
# Priority: this file > ~/.config/agentic-goal/config.yaml > defaults

default_provider: openrouter  # anthropic | openai | ollama | openrouter

# API keys are read from environment variables:
#   export ANTHROPIC_API_KEY=sk-ant-...
#   export OPENAI_API_KEY=sk-...
#   export OPENROUTER_API_KEY=sk-or-...

roles:
  planner:
    model: anthropic/claude-haiku-4-5-20251001
    temperature: 0.2
    max_tokens: 8000
  rules_advisor:
    model: anthropic/claude-haiku-4-5-20251001
  task_decomposer:
    model: anthropic/claude-haiku-4-5-20251001
  ticket_planner:
    model: anthropic/claude-haiku-4-5-20251001
  coder:
    model: anthropic/claude-haiku-4-5-20251001
    temperature: 0.1
  reviewer:
    model: anthropic/claude-haiku-4-5-20251001
    temperature: 0.0

# budgets:
#   per_goal_usd: 5.0
#   per_ticket_usd: 0.5
"""


def _require_init() -> None:
    """Exit with a friendly message if .goal/config.yaml does not exist."""
    if not PROJECT_CONFIG_PATH.exists():
        rprint(
            Panel(
                "[bold yellow]Project not initialised.[/bold yellow]\n\n"
                "Run [bold cyan]goal init[/bold cyan] first to set up config for this directory.",
                title="⚠️  Not initialised",
                border_style="yellow",
            )
        )
        raise typer.Exit(1)


def _close_checkpointer(checkpointer: Any) -> None:
    """Close the SqliteSaver's underlying connection if possible."""
    conn = getattr(checkpointer, "conn", None)
    if conn is not None:
        with contextlib.suppress(Exception):
            conn.close()


def _write_and_open(file_path: Path, content: str) -> str:
    """Write content to file_path, print path for user to edit, wait for Enter."""
    file_path.write_text(content, encoding="utf-8")
    rprint(f"\n[bold]Open and edit:[/bold] [cyan]{file_path.resolve()}[/cyan]")
    rprint("[dim]Save the file in your editor, then press Enter to continue...[/dim]")
    input()
    return file_path.read_text(encoding="utf-8")


def _ask_action(label: str, has_skip: bool = False) -> str:
    """Show numbered menu and return action string: approve | regenerate | skip | abort."""
    options = ["1) approve", "2) regenerate", "3) abort"]
    if has_skip:
        options = ["1) approve", "2) regenerate", "3) skip", "4) abort"]
    rprint(f"\n[bold]{label}[/bold]  " + "  ".join(f"[cyan]{o}[/cyan]" for o in options))
    mapping = {"1": "approve", "2": "regenerate", "3": "skip" if has_skip else "abort", "4": "abort"}
    while True:
        raw = input("Choice [1]: ").strip() or "1"
        if raw in mapping:
            return mapping[raw]
        rprint(f"[yellow]Enter {'/'.join(mapping.keys())}[/yellow]")


def _run_with_approvals(
    graph: Any, state: Any, config: dict[str, Any], goal_dir: Path
) -> dict[str, Any]:
    """Run the graph through plan / rules / tasks interrupts.

    At each pause we save the artifact as a file in goal_dir, open it in
    the editor, then ask user to approve or abort.
    """
    current = state

    while True:
        final_state = graph.invoke(current, config)

        snapshot = graph.get_state(config)
        next_nodes = tuple(snapshot.next or ())

        if not next_nodes:
            return final_state  # Pipeline finished

        next_node = next_nodes[0]

        # ---------- PLAN approval ----------
        if next_node == "plan_approval":
            plan_text = final_state.get("plan", "")
            plan_file = goal_dir / "plan.md"
            rprint(f"[dim]Saving plan to:[/dim] [cyan]{plan_file}[/cyan]")
            updated = _write_and_open(plan_file, plan_text or "")
            updated = updated.strip()
            if updated and updated != plan_text.strip():
                graph.update_state(config, {"plan": updated}, as_node="plan")
            choice = _ask_action("Plan")
            if choice == "abort":
                raise typer.Exit(1)
            if choice == "regenerate":
                fb = Prompt.ask("Feedback (what to change)")
                graph.update_state(config, {"plan": "", "feedback": fb}, as_node="__start__")
                current = None
                continue
            # approve -> reset feedback and resume
            graph.update_state(config, {"feedback": None}, as_node="plan")

        # ---------- RULES approval ----------
        elif next_node == "rules_approval":
            questions = final_state.get("rules", "")
            rules_file = goal_dir / "rules.md"
            rprint(f"[dim]Saving rules to:[/dim] [cyan]{rules_file}[/cyan]")
            updated = _write_and_open(rules_file, questions or "")
            updated = updated.strip()
            if updated:
                graph.update_state(config, {"rules": updated}, as_node="rules")
            choice = _ask_action("Rules", has_skip=True)
            if choice == "abort":
                raise typer.Exit(1)
            if choice == "regenerate":
                fb = Prompt.ask("Feedback (what to change)")
                graph.update_state(config, {"rules": "", "feedback": fb}, as_node="plan")
                current = None
                continue
            # approve / skip -> reset feedback and resume
            graph.update_state(config, {"feedback": None}, as_node="rules")

        # ---------- TASKS approval ----------
        elif next_node == "tasks_approval":
            from agentic_goal.nodes import _parse_tasks_to_kanban

            tasks_list = final_state.get("tasks") or []
            tasks_md = tasks_list[0].get("raw", "") if tasks_list else ""
            kanban = final_state.get("kanban", {})
            tasks_file = goal_dir / "tasks.md"
            rprint(
                f"[dim]Saving tasks ({len(kanban)} tickets) to:[/dim] [cyan]{tasks_file}[/cyan]"
            )
            updated = _write_and_open(tasks_file, tasks_md or "")
            updated = updated.strip()
            if updated and updated != tasks_md.strip():
                new_kanban = _parse_tasks_to_kanban(updated)
                graph.update_state(
                    config,
                    {"tasks": [{"raw": updated}], "kanban": new_kanban},
                    as_node="tasks",
                )
            choice = _ask_action("Tasks")
            if choice == "abort":
                raise typer.Exit(1)
            if choice == "regenerate":
                fb = Prompt.ask("Feedback (what to change)")
                graph.update_state(
                    config,
                    {"tasks": [], "kanban": {}, "feedback": fb},
                    as_node="rules",
                )
                current = None
                continue
            # approve -> reset feedback and resume
            graph.update_state(config, {"feedback": None}, as_node="tasks")

        else:
            # Unknown interrupt — just resume
            rprint(f"[yellow]Pausing at unknown node: {next_node}; resuming.[/yellow]")

        # Resume by passing None
        current = None


@app.command()
def init(
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing config"),
) -> None:
    """Initialise a new agentic-goal project in the current directory."""
    config_path = PROJECT_CONFIG_PATH
    if config_path.exists() and not force:
        rprint(
            Panel(
                f"[yellow]Config already exists:[/yellow] {config_path}\n\n"
                "Use [bold]goal init --force[/bold] to overwrite.",
                title="Already initialised",
                border_style="yellow",
            )
        )
        raise typer.Exit(0)

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(_CONFIG_TEMPLATE, encoding="utf-8")

    skills_dir = config_path.parent / "skills"
    skills_dir.mkdir(exist_ok=True)
    global_skill = skills_dir / "global.md"
    if not global_skill.exists():
        global_skill.write_text(
            "# Global project context\n\n"
            "<!-- Add conventions, domain knowledge, or constraints that apply to ALL agents. -->\n"
            "<!-- Examples: target language version, prohibited libraries, naming conventions. -->\n",
            encoding="utf-8",
        )

    rprint(
        Panel(
            f"[bold green]Initialised![/bold green]\n\n"
            f"Config:  [cyan]{config_path}[/cyan]\n"
            f"Skills:  [cyan]{skills_dir}/[/cyan]\n\n"
            "Next steps:\n"
            "  1. Edit [cyan].goal/config.yaml[/cyan] to set your provider & models\n"
            "  2. Export your API key, e.g.:\n"
            "     [dim]export OPENROUTER_API_KEY=sk-or-...[/dim]\n"
            "  3. (Optional) add skill files to [cyan].goal/skills/[/cyan]\n"
            "  4. Run [bold cyan]goal start \"your idea\"[/bold cyan]",
            title="✅  goal init",
            border_style="green",
        )
    )


@app.command()
def start(
    idea: str = typer.Argument(..., help="Goal idea / requirement"),
    verbose: int = typer.Option(0, "--verbose", "-v", help="Verbosity (-v, -vv, -vvv)"),
    model_override: list[str] | None = typer.Option(  # noqa: B008
        None,
        "--model-override",
        help="Override model per role, e.g. coder=gpt-4",
    ),
    no_color: bool = typer.Option(False, "--no-color"),
    json_output: bool = typer.Option(False, "--json"),
) -> None:
    """Start a new goal pipeline from an idea."""
    _require_init()
    cfg = load_config()

    # Convert None to empty list
    if model_override is None:
        model_override = []

    # Apply model overrides from CLI
    for override in model_override:
        if "=" in override:
            role, model = override.split("=", 1)
            if role in cfg.roles:
                cfg.roles[role] = cfg.roles[role].model_copy(update={"model": model})

    validate_config(cfg, strict=False)

    goal_id = f"g_{uuid.uuid4().hex[:12]}"
    goal_dir = Path(".goal") / goal_id
    goal_dir.mkdir(parents=True, exist_ok=True)

    rprint(f"[bold green]Goal:[/bold green] {idea}")
    rprint(f"[dim]Goal ID:[/dim] {goal_id}")
    rprint(f"[dim]Workspace:[/dim] {goal_dir}")

    # Set up event bus with 3 sinks
    event_bus = EventBus(goal_id)
    event_bus.add_sink(TerminalSink(verbose=verbose))
    event_bus.add_sink(JsonlSink(goal_dir / "events.jsonl"))
    event_bus.add_sink(MarkdownSink(goal_dir / "transcript.md"))

    # Set event_bus in context for nodes to access
    set_event_bus(event_bus)

    # Build graph with checkpointer
    checkpointer = get_checkpointer(goal_dir)
    try:
        graph = build_graph(checkpointer=checkpointer)

        # Initial state
        initial_state: dict[str, Any] = {
            "goal_id": goal_id,
            "idea": idea,
            "phase": "planning",
            "messages": [],
            "plan": "",
            "rules": "",
            "tasks": [],
            "current_ticket_id": None,
            "kanban": {},
            "config_override": {},
            "cumulative_cost_usd": 0.0,
            "cumulative_tokens": 0,
            "interrupt_reason": None,
            "feedback": None,
        }

        # Run graph through plan -> rules -> tasks (with human approvals)
        config: dict[str, Any] = {
            "configurable": {"thread_id": goal_id},
            "recursion_limit": 200,
        }
        try:
            final_state = _run_with_approvals(graph, initial_state, config, goal_dir)
        except Exception as exc:
            _friendly_error(exc)
            raise typer.Exit(1) from None
    finally:
        _close_checkpointer(checkpointer)
        event_bus.close()

    rprint("[bold green]✓[/bold green] Plan, rules, and tasks generated.")
    rprint(f"[dim]Artifacts saved to:[/dim] {goal_dir}/")
    raise typer.Exit(0)


@app.command("continue")
def continue_cmd(
    goal_id: str = typer.Option("", "--id", help="Goal ID to resume (default: latest)"),
    verbose: int = typer.Option(0, "--verbose", "-v", help="Verbosity (-v, -vv, -vvv)"),
) -> None:
    """Resume the most recent (or specified) goal from checkpoint."""
    _require_init()
    cfg = load_config()

    validate_config(cfg, strict=False)

    # Find goal directory
    goal_dir: Path
    if goal_id:
        goal_dir = Path(".goal") / goal_id
        if not goal_dir.exists():
            rprint(f"[bold red]Goal not found:[/bold red] {goal_id}")
            raise typer.Exit(1)
    else:
        # Find latest goal
        goals_dir = Path(".goal")
        if not goals_dir.exists():
            rprint("[bold red]No goals found.[/bold red]")
            raise typer.Exit(1)
        goal_dirs = sorted(
            (p for p in goals_dir.iterdir() if p.is_dir() and p.name.startswith("g_")),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
        if not goal_dirs:
            rprint("[bold red]No goals found.[/bold red]")
            raise typer.Exit(1)
        goal_dir = goal_dirs[0]
        goal_id = goal_dir.name

    rprint(f"[bold yellow]Resuming goal:[/bold yellow] {goal_id}")
    rprint(f"[dim]Workspace:[/dim] {goal_dir}")

    # Set up event bus with 3 sinks
    event_bus = EventBus(goal_id)
    event_bus.add_sink(TerminalSink(verbose=verbose))
    event_bus.add_sink(JsonlSink(goal_dir / "events.jsonl"))
    event_bus.add_sink(MarkdownSink(goal_dir / "transcript.md"))

    # Set event_bus in context for nodes to access
    set_event_bus(event_bus)

    # Build graph with checkpointer
    checkpointer = get_checkpointer(goal_dir)
    try:
        graph = build_graph(checkpointer=checkpointer)

        # Load checkpointed state
        config: dict[str, Any] = {
            "configurable": {"thread_id": goal_id},
            "recursion_limit": 200,
        }
        checkpoint = checkpointer.get(config)
        if not checkpoint:
            rprint("[bold red]No checkpoint found for this goal.[/bold red]")
            raise typer.Exit(1)

        # Continue execution; pass None to let LangGraph resume from checkpoint
        # and let our helper handle any pending approval interrupts.
        try:
            final_state = _run_with_approvals(graph, None, config, goal_dir)
        except Exception as exc:
            _friendly_error(exc)
            raise typer.Exit(1) from None
    finally:
        _close_checkpointer(checkpointer)
        event_bus.close()

    rprint("[bold green]✓[/bold green] Goal execution continued.")
    rprint(f"[dim]Artifacts saved to:[/dim] {goal_dir}/")
    raise typer.Exit(0)


@app.command()
def status(
    watch: bool = typer.Option(False, "--watch", help="Live update mode"),
    goal_id: str = typer.Option("", "--id", help="Goal ID"),
) -> None:
    """Show kanban + current phase."""
    # Find goal directory
    goal_dir: Path
    if goal_id:
        goal_dir = Path(".goal") / goal_id
        if not goal_dir.exists():
            rprint(f"[bold red]Goal not found:[/bold red] {goal_id}")
            raise typer.Exit(1)
    else:
        # Find latest goal
        goals_dir = Path(".goal")
        if not goals_dir.exists():
            rprint("[bold red]No goals found.[/bold red]")
            raise typer.Exit(1)
        goal_dirs = sorted(
            (p for p in goals_dir.iterdir() if p.is_dir() and p.name.startswith("g_")),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
        if not goal_dirs:
            rprint("[bold red]No goals found.[/bold red]")
            raise typer.Exit(1)
        goal_dir = goal_dirs[0]
        goal_id = goal_dir.name

    # Load checkpointed state
    checkpointer = get_checkpointer(goal_dir)
    try:
        config = {"configurable": {"thread_id": goal_id}}
        checkpoint = checkpointer.get(config)

        if not checkpoint:
            rprint("[bold red]No checkpoint found for this goal.[/bold red]")
            raise typer.Exit(1)

        state = checkpoint.get("channel_values", {})
    finally:
        _close_checkpointer(checkpointer)

    rprint(f"[bold cyan]Goal:[/bold cyan] {goal_id}")
    rprint(f"[dim]Phase:[/dim] {state.get('phase', 'unknown')}")
    rprint(f"[dim]Current ticket:[/dim] {state.get('current_ticket_id', 'none')}")

    # Show kanban
    kanban = state.get("kanban", {})
    if kanban:
        rprint("\n[bold]Kanban:[/bold]")
        for ticket_id, ticket_info in kanban.items():
            status_emoji = {
                "todo": "⏳",
                "in_progress": "🔄",
                "done": "✅",
            }.get(ticket_info.get("status"), "❓")
            rprint(f"  {status_emoji} {ticket_id}: {ticket_info.get('title', 'No title')}")

    # Show cumulative cost
    cost = state.get("cumulative_cost_usd", 0.0)
    tokens = state.get("cumulative_tokens", 0)
    rprint(f"\n[dim]Cost:[/dim] ${cost:.4f} | [dim]Tokens:[/dim] {tokens:,}")

    raise typer.Exit(0)


@app.command()
def list_goals() -> None:
    """List all goals."""
    goals_dir = Path(".goal")
    if not goals_dir.exists():
        rprint("[bold red]No goals found.[/bold red]")
        raise typer.Exit(0)

    goal_dirs = sorted(
        (p for p in goals_dir.iterdir() if p.is_dir() and p.name.startswith("g_")),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )

    rprint("[bold cyan]Goals:[/bold cyan]")
    for goal_dir in goal_dirs:
        goal_id = goal_dir.name
        # Load checkpoint to get phase
        checkpointer = get_checkpointer(goal_dir)
        try:
            config = {"configurable": {"thread_id": goal_id}}
            checkpoint = checkpointer.get(config)
            if checkpoint:
                state = checkpoint.get("channel_values", {})
                phase = state.get("phase", "unknown")
                idea = state.get("idea", "No idea")[:50]  # Truncate long ideas
            else:
                phase = "no checkpoint"
                idea = "N/A"
        finally:
            _close_checkpointer(checkpointer)

        mtime = goal_dir.stat().st_mtime
        from datetime import datetime

        time_str = datetime.fromtimestamp(mtime).strftime("%Y-%m-%d %H:%M")

        rprint(f"  [dim]{time_str}[/dim] [bold]{goal_id}[/bold] - {phase}")
        rprint(f"    [dim]{idea}[/dim]")

    raise typer.Exit(0)


@app.command()
def logs(
    goal_id: str = typer.Option("", "--id", help="Goal ID"),
    follow: bool = typer.Option(False, "--follow", help="Follow mode (not implemented)"),
    phase: str = typer.Option("", "--phase", help="Filter by phase"),
    ticket: str = typer.Option("", "--ticket", help="Filter by ticket"),
    role: str = typer.Option("", "--role", help="Filter by role"),
) -> None:
    """View agent transcript / event log."""
    # Find goal directory
    goal_dir: Path
    if goal_id:
        goal_dir = Path(".goal") / goal_id
        if not goal_dir.exists():
            rprint(f"[bold red]Goal not found:[/bold red] {goal_id}")
            raise typer.Exit(1)
    else:
        # Find latest goal
        goals_dir = Path(".goal")
        if not goals_dir.exists():
            rprint("[bold red]No goals found.[/bold red]")
            raise typer.Exit(1)
        goal_dirs = sorted(
            (p for p in goals_dir.iterdir() if p.is_dir()),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
        if not goal_dirs:
            rprint("[bold red]No goals found.[/bold red]")
            raise typer.Exit(1)
        goal_dir = goal_dirs[0]
        goal_id = goal_dir.name

    # Show transcript
    transcript_path = goal_dir / "transcript.md"
    if transcript_path.exists():
        rprint(f"[bold cyan]Transcript for {goal_id}:[/bold cyan]")
        content = transcript_path.read_text(encoding="utf-8")
        rprint(content)
    else:
        rprint("[dim]No transcript found.[/dim]")

    # Show events.jsonl if requested
    if phase or ticket or role:
        events_path = goal_dir / "events.jsonl"
        if events_path.exists():
            import json

            rprint("\n[bold cyan]Filtered events:[/bold cyan]")
            with events_path.open(encoding="utf-8") as f:
                for line in f:
                    event = json.loads(line)
                    if phase and event.get("phase") != phase:
                        continue
                    if ticket and event.get("ticket_id") != ticket:
                        continue
                    if role and event.get("role") != role:
                        continue
                    rprint(f"  {event.get('ts')} - {event.get('event_type')} - {event.get('node')}")
        else:
            rprint("[dim]No events found.[/dim]")

    raise typer.Exit(0)


@app.command()
def cost_dashboard(
    goal_id: str = typer.Option("", "--id", help="Goal ID"),
) -> None:
    """Show cost dashboard with breakdown by role/phase."""
    # Find goal directory
    goal_dir: Path
    if goal_id:
        goal_dir = Path(".goal") / goal_id
        if not goal_dir.exists():
            rprint(f"[bold red]Goal not found:[/bold red] {goal_id}")
            raise typer.Exit(1)
    else:
        # Find latest goal
        goals_dir = Path(".goal")
        if not goals_dir.exists():
            rprint("[bold red]No goals found.[/bold red]")
            raise typer.Exit(1)
        goal_dirs = sorted(
            (p for p in goals_dir.iterdir() if p.is_dir()),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
        if not goal_dirs:
            rprint("[bold red]No goals found.[/bold red]")
            raise typer.Exit(1)
        goal_dir = goal_dirs[0]
        goal_id = goal_dir.name

    # Load events for cost breakdown
    events_path = goal_dir / "events.jsonl"
    if not events_path.exists():
        rprint("[dim]No events found.[/dim]")
        raise typer.Exit(0)

    import json
    from collections import defaultdict

    # Aggregate costs by role
    costs_by_role: dict[str, float] = defaultdict(float)
    tokens_by_role: dict[str, int] = defaultdict(int)
    total_cost = 0.0
    total_tokens = 0

    with events_path.open(encoding="utf-8") as f:
        for line in f:
            event = json.loads(line)
            cost = event.get("cost_usd", 0.0)
            tokens = event.get("tokens_in", 0) + event.get("tokens_out", 0)
            role = event.get("role", "unknown")

            costs_by_role[role] += cost
            tokens_by_role[role] += tokens
            total_cost += cost
            total_tokens += tokens

    rprint(f"[bold cyan]Cost Dashboard for {goal_id}:[/bold cyan]")
    rprint(f"\n[bold]Total:[/bold] ${total_cost:.4f} | {total_tokens:,} tokens\n")

    rprint("[bold]By Role:[/bold]")
    for role, cost in sorted(costs_by_role.items(), key=lambda x: x[1], reverse=True):
        tokens = tokens_by_role[role]
        pct = (cost / total_cost * 100) if total_cost > 0 else 0
        bar = "█" * int(pct / 2)
        rprint(f"  {role:20s} ${cost:8.4f} ({pct:5.1f}%) {bar}")

    raise typer.Exit(0)


# ---- config subcommand group ----
config_app = typer.Typer(help="Manage model & provider configuration")


@config_app.command("show")
def config_show() -> None:
    """Display effective configuration and its sources."""
    cfg = load_config()
    rprint(cfg)


@config_app.command("set")
def config_set(
    role: str = typer.Argument(..., help="Role name (planner, coder, reviewer, ...)"),
    model: str = typer.Argument(..., help="Model string, e.g. anthropic/claude-opus-4"),
    provider: str = typer.Option("", "--provider"),
) -> None:
    """Set model for a role in user global config."""
    rprint(f"Set {role} -> {model}")


@config_app.command("unset")
def config_unset(role: str = typer.Argument(...)) -> None:
    """Unset a role override (revert to default)."""
    rprint(f"Unset {role}")


@config_app.command("models")
def config_models() -> None:
    """List known models, providers and pricing."""
    rprint("[bold cyan]Model registry[/bold cyan]")


@config_app.command("validate")
def config_validate() -> None:
    """Validate current config (reviewer != coder, keys present, etc)."""
    cfg = load_config()
    validate_config(cfg, strict=True)
    rprint("[bold green]Config is valid.[/bold green]")


@config_app.command("edit")
def config_edit() -> None:
    """Open global config in $EDITOR."""
    rprint("[bold yellow]Opening editor...[/bold yellow]")


app.add_typer(config_app, name="config")

if __name__ == "__main__":
    app()
