/**
 * Generate the color vocabulary safelist so the offline Tailwind bundle contains
 * every color class the agent might reach for when rendering dynamically.
 *
 * RED-testing showed agents default to slate/indigo/rose (not the documented
 * stone palette), so the bundle must cover all common families, not just one.
 *
 * Run: bun src/core/tools/preview/scripts/gen-safelist.ts
 * then: npm run build:preview-css
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const OUT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'safelist-colors.html');

const neutralFamilies = ['slate', 'gray', 'zinc', 'neutral', 'stone'];
const accentFamilies = ['red', 'rose', 'orange', 'amber', 'yellow', 'lime', 'green', 'emerald', 'teal', 'cyan', 'sky', 'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink'];
const shades = ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900', '950'];
const prefixes = ['text', 'bg', 'border', 'ring'];

const classes: string[] = [];
for (const family of [...neutralFamilies, ...accentFamilies]) {
    for (const shade of shades) {
        for (const prefix of prefixes) {
            classes.push(`${prefix}-${family}-${shade}`);
            if (prefix === 'bg' || prefix === 'border') {
                classes.push(`hover:${prefix}-${family}-${shade}`);
            }
        }
    }
}

const body = classes
    .reduce<string[][]>((rows, cls, i) => {
        if (i % 12 === 0) rows.push([]);
        rows[rows.length - 1].push(cls);
        return rows;
    }, [])
    .map((row) => `  <div class="${row.join(' ')}"></div>`)
    .join('\n');

const out = `<!--
  AUTO-GENERATED by scripts/gen-safelist.ts — do not edit by hand.
  Color vocabulary fed to the Tailwind build so dynamically-authored HTML
  renders correctly offline regardless of which palette the agent picks.
-->
<div>
${body}
</div>
`;

await writeFile(OUT, out, 'utf8');
console.log(`Wrote ${classes.length} color classes to ${OUT}`);
