import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type { Provider } from '@x/core';
import type { ProviderAdapter, CompileInput } from '@x/providers';

export interface CompileOptions {
  readonly provider: Provider;
  readonly targetRoot: string;
  readonly dryRun: boolean;
  readonly force: boolean;
}

export interface CompileResult {
  readonly written: readonly string[];
  readonly skipped: readonly string[];
  readonly conflicts: readonly string[];
}

const GENERATED_MARKER = '# generated by aix';

function hashContent(content: string): string {
  return createHash('sha256').update(content, 'utf-8').digest('hex');
}

export class Compiler {
  readonly #adapters: Record<Provider, ProviderAdapter>;

  constructor(adapters: Record<Provider, ProviderAdapter>) {
    this.#adapters = adapters;
  }

  async compile(input: CompileInput, opts: CompileOptions): Promise<CompileResult> {
    const adapter = this.#adapters[opts.provider];
    if (!adapter) {
      throw new Error(`Unknown provider: ${opts.provider}`);
    }

    const files = adapter.emit(input);
    const written: string[] = [];
    const skipped: string[] = [];
    const conflicts: string[] = [];

    for (const file of files) {
      const targetPath = join(opts.targetRoot, file.path);
      const newHash = hashContent(file.contents);

      let existingHash: string | undefined;
      let existingContent: string | undefined;
      try {
        existingContent = await readFile(targetPath, 'utf-8');
        existingHash = hashContent(existingContent);
      } catch {
        // file doesn't exist yet
      }

      if (existingHash === newHash) {
        skipped.push(file.path);
        continue;
      }

      if (opts.dryRun) {
        if (existingContent === undefined) {
          console.log(`  [plan] CREATE ${file.path}`);
        } else {
          console.log(`  [plan] UPDATE ${file.path}`);
        }
        written.push(file.path);
        continue;
      }

      if (existingContent !== undefined && !opts.force) {
        const hasGeneratedMarker = existingContent.includes(GENERATED_MARKER);
        if (!hasGeneratedMarker) {
          conflicts.push(file.path);
          continue;
        }
      }

      const dir = dirname(targetPath);
      await mkdir(dir, { recursive: true });

      if (file.mode !== undefined) {
        await writeFile(targetPath, file.contents, { mode: file.mode });
      } else {
        await writeFile(targetPath, file.contents, 'utf-8');
      }

      written.push(file.path);
    }

    return { written, skipped, conflicts };
  }
}
