import type { Provider } from '@x/core';
import type { ProviderAdapter, CompileInput, EmittedFile, RuleDoc } from '../types.js';

const HEADER = '# generated by aix\n\n';
const FRONTMATTER_HEADER = '---\n# generated by aix\n';

export class ClaudeAdapter implements ProviderAdapter {
  readonly id: Provider = 'claude';

  emit(input: CompileInput): readonly EmittedFile[] {
    const files: EmittedFile[] = [];

    for (const skill of input.skills) {
      files.push({
        path: `content/skills/${skill.id}/SKILL.md`,
        contents: `${FRONTMATTER_HEADER}name: ${skill.frontmatter.name}\ndescription: ${skill.frontmatter.description}\nx-kind: ${skill.frontmatter['x-kind']}\nx-version: ${skill.frontmatter['x-version']}\nx-tags: [${skill.frontmatter['x-tags'].join(', ')}]\nx-roles: [${skill.frontmatter['x-roles'].join(', ')}]\nx-compatible: [${skill.frontmatter['x-compatible'].join(', ')}]\n---\n\n${skill.body}`,
      });
    }

    for (const agent of input.agents) {
      files.push({
        path: `.claude/agents/${agent.name}.md`,
        contents: `${HEADER}# ${agent.name}\n\n${agent.description}\n\n${agent.systemPrompt}`,
      });
    }

    if (input.rules.length > 0) {
      const rulesContent = [...input.rules]
        .sort((a: RuleDoc, b: RuleDoc) => (b.priority ?? 0) - (a.priority ?? 0))
        .map((r: RuleDoc) => `## ${r.name}\n\n${r.content}`)
        .join('\n\n');
      files.push({
        path: 'CLAUDE.md',
        contents: `${HEADER}${rulesContent}`,
      });
    }

    files.push({
      path: '.claude-plugin/plugin.json',
      contents: JSON.stringify({
        name: 'aix',
        version: '0.1.0',
        description: 'AI Engineering Platform',
        author: {
          name: 'truongdq',
          url: 'https://github.com/truongnat',
        },
        skills: ['./content/skills/'],
      }, null, 2),
    });

    const hooks: Record<string, { command: string }[]> = {};
    for (const skill of input.skills) {
      for (const script of skill.scripts) {
        const hookType = script.endsWith('.pre.js') ? 'preToolUse'
          : script.endsWith('.post.js') ? 'postToolUse'
          : 'preToolUse';
        if (!hooks[hookType]) hooks[hookType] = [];
        hooks[hookType]!.push({ command: script });
      }
    }

    files.push({
      path: '.claude/settings.json',
      contents: JSON.stringify({
        hooks,
      }, null, 2),
    });

    return files;
  }
}
