import type { Provider } from '@x/core';
import type { ProviderAdapter, CompileInput, EmittedFile } from '../types.js';

const HEADER = '# generated by aix\n\n';

export class CodexAdapter implements ProviderAdapter {
  readonly id: Provider = 'codex';

  emit(input: CompileInput): readonly EmittedFile[] {
    const files: EmittedFile[] = [];

    const rulesSection = input.rules
      .map(r => `## ${r.name}\n\n${r.content}`)
      .join('\n\n');

    const skillIndex = input.catalog
      .map(s => `- ${s.name}: ${s.description} (${s.kind}, v${s.version})`)
      .join('\n');

    const agentsSection = input.agents
      .map(a => `### ${a.name}\n\n${a.description}\n\n${a.systemPrompt}`)
      .join('\n\n');

    files.push({
      path: 'AGENTS.md',
      contents: `${HEADER}# Skills\n\n${skillIndex}\n\n# Rules\n\n${rulesSection}\n\n# Agents\n\n${agentsSection}`,
    });

    return files;
  }
}
