import type { AgentDef, CompileInput, RuleDoc } from '../types.js';

export const HEADER = '# generated by aix\n\n';
const FRONTMATTER_HEADER = '---\n# generated by aix\n';

function yamlString(value: string): string {
  return JSON.stringify(value);
}

function yamlArray(values: readonly string[]): string {
  return `[${values.map(yamlString).join(', ')}]`;
}

export function renderSkillFile(skill: CompileInput['skills'][number]): string {
  return `${FRONTMATTER_HEADER}name: ${yamlString(skill.frontmatter.name)}\ndescription: ${yamlString(skill.frontmatter.description)}\nx-kind: ${yamlString(skill.frontmatter['x-kind'])}\nx-version: ${yamlString(skill.frontmatter['x-version'])}\nx-tags: ${yamlArray(skill.frontmatter['x-tags'])}\nx-roles: ${yamlArray(skill.frontmatter['x-roles'])}\nx-compatible: ${yamlArray(skill.frontmatter['x-compatible'])}\n---\n\n${skill.body}`;
}

export function renderSkillIndex(input: CompileInput): string {
  const entries = input.catalog.length > 0
    ? input.catalog
    : input.skills.map(skill => ({
      name: skill.frontmatter.name,
      description: skill.frontmatter.description,
      kind: skill.frontmatter['x-kind'],
      version: skill.frontmatter['x-version'],
      tags: skill.frontmatter['x-tags'],
    }));

  const lines = entries
    .map(skill => `- ${skill.name}: ${skill.description} (${skill.kind}, v${skill.version})`)
    .join('\n');

  return `${HEADER}# aix Skill Index\n\nSearch this file for relevant skills, then open the matching skill file before acting.\n\n${lines}\n`;
}

export function renderRulesFile(rules: readonly RuleDoc[]): string {
  const content = [...rules]
    .sort((a, b) => (b.priority ?? 0) - (a.priority ?? 0))
    .map(rule => `## ${rule.name}\n\n${rule.content}`)
    .join('\n\n');

  return `${HEADER}# aix Rules\n\n${content}\n`;
}

export function renderAgentIndex(agents: readonly AgentDef[]): string {
  const lines = agents
    .map(agent => `- ${agent.name}: ${agent.description}`)
    .join('\n');

  return `${HEADER}# aix Agent Index\n\n${lines}\n`;
}

export function renderAgentFile(agent: AgentDef): string {
  return `${HEADER}# ${agent.name}\n\n${agent.description}\n\n${agent.systemPrompt}`;
}
