import type { Provider } from '@x/core';
import type { ProviderAdapter, CompileInput, EmittedFile } from '../types.js';

const HEADER = '# generated by aix\n\n';
const FRONTMATTER_HEADER = '---\n# generated by aix\n';

function yamlString(value: string): string {
  return JSON.stringify(value);
}

export class CursorAdapter implements ProviderAdapter {
  readonly id: Provider = 'cursor';

  emit(input: CompileInput): readonly EmittedFile[] {
    const files: EmittedFile[] = [];

    for (const rule of input.rules) {
      files.push({
        path: `.cursor/rules/${rule.name}.mdc`,
        contents: `${HEADER}${rule.content}`,
      });
    }

    for (const skill of input.skills) {
      files.push({
        path: `.cursor/rules/aix-skill-${skill.id}.mdc`,
        contents: `${FRONTMATTER_HEADER}description: ${yamlString(skill.frontmatter.description)}\nglobs: "*"\nalwaysApply: false\n---\n\n# ${skill.frontmatter.name}\n\n${skill.body}`,
      });
    }

    return files;
  }
}
