import type { Provider } from '@x/core';
import type { ProviderAdapter, CompileInput, EmittedFile } from '../types.js';

const HEADER = '# generated by aix\n\n';

export class CursorAdapter implements ProviderAdapter {
  readonly id: Provider = 'cursor';

  emit(input: CompileInput): readonly EmittedFile[] {
    const files: EmittedFile[] = [];

    for (const rule of input.rules) {
      files.push({
        path: `.cursor/rules/${rule.name}.mdc`,
        contents: `${HEADER}${rule.content}`,
      });
    }

    for (const skill of input.skills) {
      files.push({
        path: `SKILL.md`,
        contents: `${HEADER}---\nname: ${skill.frontmatter.name}\ndescription: ${skill.frontmatter.description}\nx-kind: ${skill.frontmatter['x-kind']}\n---\n\n${skill.body}`,
      });
    }

    return files;
  }
}
