import type { Provider } from '@x/core';
import type { ProviderAdapter, CompileInput, EmittedFile } from '../types.js';

const HEADER = '# generated by aix\n\n';

export class GeminiAdapter implements ProviderAdapter {
  readonly id: Provider = 'gemini';

  emit(input: CompileInput): readonly EmittedFile[] {
    const files: EmittedFile[] = [];

    const rulesContent = input.rules
      .map(r => `## ${r.name}\n\n${r.content}`)
      .join('\n\n');

    const skillIndex = input.catalog
      .map(s => `- ${s.name}: ${s.description} (${s.kind}, v${s.version})`)
      .join('\n');

    const agentsSection = input.agents
      .map(a => `### ${a.name}\n\n${a.description}\n\n${a.systemPrompt}`)
      .join('\n\n');

    files.push({
      path: 'GEMINI.md',
      contents: `${HEADER}# Skills\n\n${skillIndex}\n\n# Rules\n\n${rulesContent}\n\n# Agents\n\n${agentsSection}`,
    });

    for (const skill of input.skills) {
      files.push({
        path: `skills/${skill.id}.md`,
        contents: `${HEADER}---\nname: ${skill.frontmatter.name}\ndescription: ${skill.frontmatter.description}\nx-kind: ${skill.frontmatter['x-kind']}\nx-version: ${skill.frontmatter['x-version']}\n---\n\n${skill.body}`,
      });
    }

    for (const agent of input.agents) {
      files.push({
        path: `agents/${agent.name}.md`,
        contents: `${HEADER}# ${agent.name}\n\n${agent.description}\n\n${agent.systemPrompt}`,
      });
    }

    files.push({
      path: 'gemini-extension.json',
      contents: JSON.stringify({
        name: 'aix',
        version: '0.1.0',
        description: 'AI Engineering Platform',
        skills: input.skills.map(s => s.id),
        agents: input.agents.map(a => a.name),
        mcpServers: input.mcpServers.map(s => ({ name: s.name, transport: s.transport })),
      }, null, 2),
    });

    return files;
  }
}
