import { test } from 'node:test';
import assert from 'node:assert/strict';
import { ClaudeAdapter, CodexAdapter, CursorAdapter, GeminiAdapter } from '../dist/index.js';

function skill(id) {
  return {
    id,
    dir: `/tmp/${id}`,
    frontmatter: {
      name: id,
      description: `${id} description`,
      'x-kind': 'workflow',
      'x-version': '1.0.0',
      'x-tags': ['test'],
      'x-roles': [],
      'x-compatible': ['claude', 'codex', 'cursor', 'gemini'],
    },
    body: `${id} body`,
    bodyTokenEstimate: 10,
    references: [],
    scripts: [],
    assets: [],
  };
}

const input = {
  skills: [skill('planning')],
  catalog: [],
  agents: [],
  rules: [],
  mcpServers: [],
};

function parseFrontmatter(contents) {
  assert.ok(contents.startsWith('---\n'), 'frontmatter must start at byte 0');

  const end = contents.indexOf('\n---\n', 4);
  assert.ok(end > 0, 'frontmatter must have a closing fence');

  const frontmatter = contents
    .slice(4, end)
    .split('\n')
    .filter(line => line.trim() !== '' && !line.trimStart().startsWith('#'));

  return Object.fromEntries(frontmatter.map(line => {
    const separator = line.indexOf(':');
    assert.ok(separator > 0, `invalid frontmatter line: ${line}`);
    return [line.slice(0, separator), line.slice(separator + 1).trim()];
  }));
}

test('skill and Cursor rule artefacts put frontmatter before the generated marker', () => {
  const artefacts = [
    new ClaudeAdapter().emit(input).find(file => file.path === 'content/skills/planning/SKILL.md'),
    new CursorAdapter().emit(input).find(file => file.path === '.cursor/rules/aix-skill-planning.mdc'),
    new CodexAdapter().emit(input).find(file => file.path === '.codex/skills/planning.md'),
    new GeminiAdapter().emit(input).find(file => file.path === 'skills/planning.md'),
  ];

  for (const artefact of artefacts) {
    assert.ok(artefact, 'expected artefact to be emitted');
    const data = parseFrontmatter(artefact.contents);

    assert.ok(artefact.contents.includes('# generated by aix'), 'generated marker must remain for overwrite detection');
    assert.match(data.description || data.name, /planning/);
  }
});
