import { redact } from '@x/policy';

export interface ModelCallOptions {
  readonly system: string;
  readonly user: string;
  readonly temperature?: number;
  readonly maxTokens?: number;
}

export interface ModelCallResponse {
  readonly content: string;
  readonly tokens: number;
  readonly usd: number;
}

export interface RuntimeProvider {
  readonly id: string;
  call(opts: ModelCallOptions): Promise<ModelCallResponse>;
}

function generateMockResponse(opts: ModelCallOptions): string {
  const task = opts.user;
  const lower = task.toLowerCase();

  if (lower.includes('function') || lower.includes('implement')) {
    return `// Generated by aix engine — ${opts.system.split('\n')[0] ?? 'implementation'}
// Task: ${task}

/**
 * implements the described functionality
 */
export function solution(input: unknown): unknown {
  return input;
}

export default solution;
`;
  }

  if (lower.includes('api') || lower.includes('route') || lower.includes('handler')) {
    return `// Generated by aix engine — API route handler
// Task: ${task}

import { Request, Response } from 'express';

export async function handler(req: Request, res: Response): Promise<void> {
  try {
    const result = { success: true, data: req.body };
    res.status(200).json(result);
  } catch (err) {
    res.status(500).json({ success: false, error: String(err) });
  }
}
`;
  }

  if (lower.includes('class') || lower.includes('component') || lower.includes('react')) {
    return `// Generated by aix engine — Component
// Task: ${task}

import { useState, useEffect } from 'react';

export interface ComponentProps {
  readonly title?: string;
  readonly onAction?: () => void;
}

export function SolutionComponent({ title, onAction }: ComponentProps) {
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    setLoaded(true);
  }, []);

  if (!loaded) return <div>Loading...</div>;

  return (
    <div>
      <h1>{title ?? 'Solution'}</h1>
      <button onClick={onAction}>Execute</button>
    </div>
  );
}

export default SolutionComponent;
`;
  }

  if (lower.includes('config') || lower.includes('setup') || lower.includes('script')) {
    return `// Generated by aix engine — Config/Script
// Task: ${task}

export const config = {
  name: 'solution',
  version: '1.0.0',
  environment: process.env.NODE_ENV ?? 'development',
  settings: {
    timeout: 5000,
    retries: 3,
    debug: process.env.DEBUG === 'true',
  },
};

export function setup(): void {
  console.log('[setup] initialized');
}
`;
  }

  return `// Generated by aix engine
// Task: ${task}

export function solution(): string {
  return 'implementation for: ' + ${JSON.stringify(task)};
}
`;
}

export class MockRuntimeProvider implements RuntimeProvider {
  readonly id = 'mock';

  async call(opts: ModelCallOptions): Promise<ModelCallResponse> {
    const content = generateMockResponse(opts);
    const tokens = Math.ceil(content.length / 4);
    return { content, tokens, usd: 0.001 };
  }
}

export class ApiRuntimeProvider implements RuntimeProvider {
  readonly id: string;
  readonly #apiKey: string;
  readonly #apiUrl: string;
  readonly #model: string;

  constructor() {
    this.id = process.env.AIX_PROVIDER ?? 'anthropic';
    this.#apiKey = process.env.ANTHROPIC_API_KEY ?? process.env.OPENAI_API_KEY ?? '';
    this.#apiUrl = this.id === 'anthropic'
      ? 'https://api.anthropic.com/v1/messages'
      : 'https://api.openai.com/v1/chat/completions';
    this.#model = this.id === 'anthropic'
      ? (process.env.ANTHROPIC_MODEL ?? 'claude-sonnet-4-6')
      : (process.env.OPENAI_MODEL ?? 'gpt-4o');
  }

  async call(opts: ModelCallOptions): Promise<ModelCallResponse> {
    if (!this.#apiKey) {
      console.warn('[provider] No API key found (ANTHROPIC_API_KEY or OPENAI_API_KEY). Falling back to mock.');
      return new MockRuntimeProvider().call(opts);
    }

    if (this.id === 'anthropic') {
      return this.#callAnthropic(opts);
    }
    return this.#callOpenAI(opts);
  }

  async #callAnthropic(opts: ModelCallOptions): Promise<ModelCallResponse> {
    const res = await fetch(this.#apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': this.#apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: this.#model,
        system: opts.system,
        messages: [{ role: 'user', content: opts.user }],
        max_tokens: opts.maxTokens ?? 4096,
        temperature: opts.temperature ?? 0.7,
      }),
    });

    if (!res.ok) {
      const result = redact(await res.text());
      throw new Error(`Anthropic API error: ${res.status} ${result.clean}`);
    }

    const data = await res.json() as {
      content: Array<{ text: string }>;
      usage: { input_tokens: number; output_tokens: number };
    };

    const content = data.content.map(c => c.text).join('\n');
    const tokens = data.usage.input_tokens + data.usage.output_tokens;
    const usd = (data.usage.input_tokens * 3 + data.usage.output_tokens * 15) / 1_000_000;

    return { content, tokens, usd };
  }

  async #callOpenAI(opts: ModelCallOptions): Promise<ModelCallResponse> {
    const res = await fetch(this.#apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${this.#apiKey}`,
      },
      body: JSON.stringify({
        model: this.#model,
        messages: [
          { role: 'system', content: opts.system },
          { role: 'user', content: opts.user },
        ],
        max_tokens: opts.maxTokens ?? 4096,
        temperature: opts.temperature ?? 0.7,
      }),
    });

    if (!res.ok) {
      const result = redact(await res.text());
      throw new Error(`OpenAI API error: ${res.status} ${result.clean}`);
    }

    const data = await res.json() as {
      choices: Array<{ message: { content: string } }>;
      usage: { prompt_tokens: number; completion_tokens: number };
    };

    const content = data.choices[0]?.message?.content ?? '';
    const tokens = data.usage.prompt_tokens + data.usage.completion_tokens;
    const usd = (data.usage.prompt_tokens * 2.5 + data.usage.completion_tokens * 10) / 1_000_000;

    return { content, tokens, usd };
  }
}

export function createProvider(): RuntimeProvider {
  if (process.env.ANTHROPIC_API_KEY || process.env.OPENAI_API_KEY) {
    return new ApiRuntimeProvider();
  }
  console.warn('[provider] No API key configured. Using mock provider. Set ANTHROPIC_API_KEY or OPENAI_API_KEY.');
  return new MockRuntimeProvider();
}
